version: '2'
services:
  app:
    build:
      context: ./
      dockerfile: docker/app.dockerfile
    working_dir: /var/www
    volumes:
      - './:/var/www'
    environment:
      - DB_PORT=3306
      - DB_HOST=database
    depends_on:
      - database
  web:
    build:
      context: ./
      dockerfile: docker/web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - '80:80'
  database:
    image: 'mysql:5.7'
    volumes:
      - 'dbdata:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
    ports:
      - '3306:3306'
volumes:
  dbdata: null
